### ISSUE TITLE
ios工程路径下的main.js和libraries文件缺失

### ISSUE THREAD

**Issue by ZXSGG** [tomoya92/ITNews-React-Native#2]
![erro1](https://user-images.githubusercontent.com/8485995/29806639-045dfbfa-8cc3-11e7-86a0-bb0054ce9c53.png)
appDelegate文件没有找到相应头文件
![error2](https://user-images.githubusercontent.com/8485995/29806658-19ba42a6-8cc3-11e7-96ef-1ce9a88af52a.png)

**Comment by atjiu** [comment]
@cheniuiOSloved 确实没有main.jsbundle

但libraries是有的

**Comment by ZXSGG** [comment]
@tomoya92 并没有，libraries的name 已经标红，表示的是文件缺失。你那边是用什么管理的第三方库集成？

**Comment by atjiu** [comment]
@cheniuiOSloved 没有用什么管理，项目用react-native init xxx 初始化的，然后仅仅用xcode打开了项目下ios文件夹里的xxx.xcodeproj文件而已
